/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-10 03:25:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>회원가입</h3>\r\n");
      out.write("\t<form name=\"writeForm\" method=\"post\" action=\"write.jsp\">\r\n");
      out.write("\t\t<table border=\"1\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--1행-->\r\n");
      out.write("\t\t\t\t<td width=\"70\" align=\"center\">이 름</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"name\" id=\"name\" placeholder=\"이름 입력\" ></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--2행-->\r\n");
      out.write("\t\t\t\t<td width=\"70\" align=\"center\">아이디</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"id\" placeholder=\"아이디 입력\" size=\"30\" onkeyup=\"inputIdChk()\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"중복체크\" onclick=\"checkId()\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"idDuplication\" value=\"idUncheck\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--3행-->\r\n");
      out.write("\t\t\t\t<td width=\"70\" align=\"center\">비밀번호</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"pwd\" size=\"30\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--4행-->\r\n");
      out.write("\t\t\t\t<td width=\"70\" align=\"center\">재확인</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"repwd\" size=\"30\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--5행-->\r\n");
      out.write("\t\t\t\t<td align=\"center\">성별</td>\r\n");
      out.write("\t\t\t\t<td><label/><input type='radio' name='gender' value='0' />남성 &emsp;\r\n");
      out.write("\t\t\t\t\t<label/><input type='radio' name='gender' value='1' checked />여성</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">이 메 일</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"email1\" size=\"10\">@ \r\n");
      out.write("\t\t\t\t<input type=\"email\" name=\"email2\" list=\"defaultEmails\"> \r\n");
      out.write("\t\t\t\t<datalist id=\"defaultEmails\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"naver.com\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"gmail.com\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"hanmail.net\">\r\n");
      out.write("\t\t\t\t\t</datalist></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--7행-->\r\n");
      out.write("\t\t\t\t<td align=\"center\">핸드폰</td>\r\n");
      out.write("\t\t\t\t<td><select name=\"tel1\" style=\"width: 50px\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t&nbsp;-&nbsp; \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"tel2\" size=\"3\">\r\n");
      out.write("\t\t\t\t&nbsp;-&nbsp; \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"tel3\" size=\"3\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--8행-->\r\n");
      out.write("\t\t\t\t<td width=\"70\" align=\"center\">주소</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"zipcode\" id=\"zipcode\" readonly size=\"7\"> \r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"우편번호검색\" onclick=\"checkPost()\"><br> \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"addr1\" id=\"addr1\" placeholder=\"주소\" size=\"50\" readonly><br> \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"addr2\" id=\"addr2\" placeholder=\"상세 주소\" size=\"50\" ></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!--9행-->\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"회원가입\" onclick=\"checkWriteForm()\"> &emsp;\r\n");
      out.write("\t\t\t    <input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("\t\t\t    <input type=\"button\" value=\"로그인\" onclick=\"javascrpit:location.href='loginForm.jsp'\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<img src=\"../image/bb.PNG\" width=150>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/member.js\"> //http://localhost:8080/memberServlet/js/member.js\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
